%%
%% Autogenerated by Thrift Compiler (0.13.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-ifndef(_msg_service_included).
-define(_msg_service_included, yeah).
-include("msg_types.hrl").

-endif.
