%%
%% Autogenerated by Thrift Compiler (0.13.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(msg_service_thrift).
-behaviour(thrift_service).


-include("msg_service_thrift.hrl").

-export([struct_info/1, function_info/2, function_names/0]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% hello(This, M)
function_info('hello', params_type) ->
  {struct, [{1, {struct, {'msg_types', 'msg.Message'}}}]}
;
function_info('hello', reply_type) ->
  {struct, {'msg_types', 'msg.Message'}};
function_info('hello', exceptions) ->
  {struct, []}
;
% AddUser(This, Info)
function_info('AddUser', params_type) ->
  {struct, [{1, {struct, {'msg_types', 'msg.UserInfo'}}}]}
;
function_info('AddUser', reply_type) ->
  {struct, {'msg_types', 'msg.ServerReply'}};
function_info('AddUser', exceptions) ->
  {struct, []}
;
% UpdateUser(This, Info)
function_info('UpdateUser', params_type) ->
  {struct, [{1, {struct, {'msg_types', 'msg.UserInfo'}}}]}
;
function_info('UpdateUser', reply_type) ->
  {struct, {'msg_types', 'msg.ServerReply'}};
function_info('UpdateUser', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

function_names() -> 
  ['hello', 'AddUser', 'UpdateUser'].

