%%
%% Autogenerated by Thrift Compiler (0.12.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(msg_types).

-include("msg_types.hrl").

-export([struct_info/1, struct_info_ext/1, enum_info/1, enum_names/0, struct_names/0, exception_names/0]).

struct_info('msg.Message') ->
  {struct, [{1, i64},
          {2, string}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('msg.Message') ->
  {struct, [{1, required, i64, 'id', undefined},
          {2, required, string, 'text', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

struct_names() ->
  ['msg.Message'].

enum_info(_) -> erlang:error(function_clause).

enum_names() ->
  [].

exception_names() ->
  [].

