[package]
name = "example"
version = "0.1.0"
authors = ["Peter Mezei <mezeipetister@gmail.com>"]
publish = false

[dependencies]
env_logger = "0.5.12"
log = "0.4.4"
ordered-float = "2.0.1"
try_from = "0.2.2"
thrift = "0.0.4"